# -*- coding: utf-8 -*-
"""BloodCellnew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-ZeNID-o0D_dRvUH_lUUltahflYfiGz

#Code to Install Libraries
"""

# Ultralytics YOLO ve PyTorch kütüphanelerini yükleme kodu
!pip install ultralytics
!pip install torch

"""# Training"""

import os # Dosya ve dizin işlemleri için gerekli modül
from ultralytics import YOLO  # YOLO modeli için ultralytics kütüphanesi
import torch  # PyTorch kütüphanesi; tensor işlemleri ve GPU kullanımı için

# GPU kullanımı kontrolü: CUDA mevcutsa cuda, değilse cpu kullanması için
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Veri setinin bulunduğu path
DATA_DIR = "/content/drive/MyDrive/bloodcellProject/Data.b"

# YOLO sınıflandırma modeli yüklmesi; 'yolov8x-cls.pt'
model = YOLO("yolov8x-cls.pt")


# Modelin eğitimi başlatılır
results = model.train(data=DATA_DIR,  # Eğitim verilerinin dizini
                      project='/content/drive/MyDrive/bloodcellProject/runs_bloodcell', # Eğitim sonuçlarının kaydedileceği dizin
                      epochs=5, # Eğitim döngüsü sayısı (epoch)
                      auto_augment = False, # Otomatik veri artırma (augmentation) devre dışı
                      mixup = 0,  # Veri karıştırma tekniği (mixup) devre dışı
                      shear= 0, # Görüntü kesme (shear) işlemi devre dışı
                      erasing = 0,  # Rastgele silme (random erasing) devre dışı
                      imgsz=500,  # Eğitim sırasında kullanılacak görüntü boyutu (500x500 piksel)
                      lr0=0.001,  # Başlangıç öğrenme oranı (learning rate)
                      optimizer='Adam', # Kullanılacak optimizasyon algoritması: Adam
                      cache=True) # Veri setinin önbelleğe alınması; eğitim sürecini hızlandırır
